development:
  adapter: postgresql
  encoding: unicode
  database: sample_postgres_development
  pool: 5
  username: detention_development
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: sample_postgres_test
  pool: 5
  username: detention_test
  password:
