development:
  adapter: postgresql
  encoding: unicode
  database: detention_development
  pool: 5
  username: 
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: detention_test
  pool: 5
  username:
  password:
